AllCops:
  Includes:
    - '*.gemspec'
    - '*.rake'
    - '*.dotum'
    - '.guardrc'
    - '.simplecov'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  Excludes:
    - 'extern/*'

AmbiguousOperator:
  Enabled: false

BracesAroundHashParameters:
  Exclude:
    - 'spec/*'

CyclomaticComplexity:
  Max: 8

Documentation:
  Exclude:
    - 'spec/*'

HashSyntax:
  # We have to support 1.8.
  EnforcedStyle: hash_rockets

LineLength:
  Max: 80

MethodLength:
  Max: 20

RegexpLiteral:
  MaxSlashes: 0

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

TrivialAccessors:
  AllowPredicates: true
  ExactNameMatch: true

WordArray:
  Enabled: false
