AllCops:
  Includes:
    - '*.gemspec'
    - '*.rake'
    - '*.dotum'
    - '.guardrc'
    - '.simplecov'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  Excludes:
    - 'extern/*'

# AssignmentInCondition:
#   AllowSafeAssignment: true

BracesAroundHashParameters:
  Exclude:
    - 'spec/*'

Documentation:
  Exclude:
    - 'spec/*'

HashSyntax:
  # We have to support 1.8.
  EnforcedStyle: hash_rockets

LineLength:
  Max: 80

MethodLength:
  Max: 20

# RegexpLiteral:
#   MaxSlashes: 0

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# TrailingBlankLines:
#   Enabled: false

# TrivialAccessors:
#   AllowPredicates: true
#   ExactNameMatch: true

# WordArray:
#   Enabled: false

# # Temp
# LineLength:
#   Enabled: false
